namespace: default

app:
  name: java-sample
  tag: latest
  registry: taco-registry:5000

deployment:
  # image: java-sample:latest
  replicaCount: 1

  # resources: 
  #   limits:
  #     cpu: 1000m
  #     memory: 2048Mi
  #   requests:
  #     cpu: 1000m
  #     memory: 2048Mi

  env:
    - name: DB_HOST
      value: "exntu.kr"
    - name: DB_PORT
      value: "33306"
    - name: REDIS_HOST
      value: "exntu.kr"
    - name: REDIS_PORT
      value: "26379"

  hostAliases: []
#    - ip: "192.168.1.10"
#      hostnames:
#      - "sample.com"
#      - "www.sample.com"

  nodeSelector: {}
  affinity: {}
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: kubernetes.io/hostname
#            operator: In
#            values:
#            - master3

  livenessProbe:
    enabled: true
    path: /health
    port: 8080
    initialDelaySeconds:
    timeoutSeconds:

  readinessProbe:
    enabled: true
    path: /health
    port: 8080
    initialDelaySeconds:
    timeoutSeconds:

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

service:
  enabled: true
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort:

ingress:
  enabled: false
  annotations: {}
  host: app.example.java
  paths:
    - path: /
      port: 8080



