namespace: jenkins

app:
  name: java-app-example
  tag: v1
  registry: taco-registry:5000

deployment:
  replicaCount: 3

  resources: 
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi

  env:
    - name: DB_HOST
      value: "ex-host"
    - name: DB_PORT
      value: "3306"
    - name: REDIS_HOST
      value: "ex-host"
    - name: REDIS_PORT
      value: "6379"

  livenessProbe:
    enabled: true
    path: /health
    port: 8080
    initialDelaySeconds:
    timeoutSeconds:

  readinessProbe:
    enabled: true
    path: /health
    port: 8080
    initialDelaySeconds:
    timeoutSeconds:

service:
  enabled: true
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31111

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false

