{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.tag }}
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- $root := . -}}
      {{- range .Values.ingress.paths }}
      - path: {{ .path }}
        backend:
          serviceName: {{ $root.Values.app.name }}-{{ $root.Values.app.tag }}
          servicePort: {{ .port }}
      {{- end }}
{{ end }}
