{{ if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.tag }}
  labels:
    app: {{ .Values.app.name }}
    tag: {{ .Values.app.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end}}
  selector:
    app: {{ .Values.app.name }}
{{ end }}
